(function() {
    "use strict";

    const app = window.app;

    const requestHeaders = [
        "Accept",
        "Accept-Charset",
        "Accept-Datetime",
        "Accept-Encoding",
        "Accept-Language",
        "Authorization",
        "Cache-Control",
        "Connection",
        "Content-Length",
        "Content-MD5",
        "Content-Type",
        "Cookie",
        "Date",
        "Expect",
        "Forwarded",
        "From",
        "Front-End-Https",
        "Host",
        "If-Match",
        "If-Modified-Since",
        "If-None-Match",
        "If-Range",
        "If-Unmodified-Since",
        "Max-Forwards",
        "Origin",
        "Pragma",
        "Proxy-Authorization",
        "Range",
        "Referer",
        "TE",
        "Trailer",
        "Transfer-Encoding",
        "Upgrade",
        "User-Agent",
        "Via",
        "Warning",
        "X-Csrf-Token",
        "X-Forwarded-For",
        "X-Forwarded-Host",
        "X-Forwarded-Port",
        "X-Forwarded-Proto",
        "X-Http-Method-Override"
    ];

    const responseHeaders = [
        "Accept-Patch",
        "Accept-Ranges",
        "Access-Control-Allow-Origin",
        "Age",
        "Allow",
        "Cache-Control",
        "Connection",
        "Content-Disposition",
        "Content-Encoding",
        "Content-Language",
        "Content-Length",
        "Content-Location",
        "Content-MD5",
        "Content-Range",
        "Content-Security-Policy",
        "Content-Type",
        "Date",
        "ETag",
        "Expires",
        "Last-Modified",
        "Link",
        "Location",
        "Pragma",
        "Proxy-Authenticate",
        "Refresh",
        "Retry-After",
        "Server",
        "Set-Cookie",
        "Status",
        "Strict-Transport-Security",
        "TSV",
        "Trailer",
        "Transfer-Encoding",
        "Upgrade",
        "Upgrade-Insecure-Requests",
        "Vary",
        "Via",
        "WWW-Authenticate",
        "Warning",
        "X-Content-Duration",
        "X-Content-Security-Policy",
        "X-Content-Type-Options",
        "X-Frame-Options",
        "X-Powered-By",
        "X-UA-Compatible",
        "X-WebKit-CSP",
        "X-XSS-Protection"
    ];

    app.headersLists = {
        requestHeaders: requestHeaders,
        responseHeaders: responseHeaders
    };
})();
